### ISSUE TITLE
Add warning /error messages for user?

### ISSUE THREAD

**Issue by dbmri** [dbnyu/BirdcageBuilder2023#6]
All debug stuff is going to console.log() now (and possibly will be disabled for production/release).

Are there error cases where we need to display a verbose error message to the user?

Input validation #5 
Stale output #4 or bad input on subsequent calculations (ie. besides just resetting table output, tell the user what's wrong?)
- or will input validation clarify most of these cases?

**Comment by dbnyu** [comment]
Input validation & stale input now work for subsequent calculations after 1st calculation
